if(USE_SYSTEM_ZLIB)
    list(REMOVE_ITEM CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
    find_package(ZLIB)
    list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
else()
    if(TARGET zlibstatic)
        if(NOT TARGET ZLIB::ZLIB)
            add_library(ZLIB::ZLIB ALIAS zlibstatic)
        endif()
        set(ZLIB_FOUND TRUE)
        set(ZLIB_LIBRARIES ZLIB::ZLIB)
        set(ZLIB_INCLUDE_DIRS "${CMAKE_SOURCE_DIR}/3rdparty/zlib/zlib" "${CMAKE_BINARY_DIR}/3rdparty/zlib/zlib")
    else()
        message(FATAL_ERROR "zlibstatic target not found. Ensure 3rdparty/zlib is added before find_package(ZLIB).")
    endif()
endif()
